<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PRRX.InternetDownloadManager</AssemblyName>
    <RootNamespace>PRRX.IDM</RootNamespace>
    <Company>PRRX Cooperation</Company>
    <Product>PRRX Internet Download Manager</Product>
    <Description>Enterprise-Grade High-Performance Windows Internet Download Manager</Description>
    <Copyright>Copyright © 2026 PRRX Cooperation. All Rights Reserved. PRRX IDM™ - Confidential &amp; Proprietary Engine</Copyright>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <Version>1.4.0</Version>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    
    <!-- Application Icon -->
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>

    <!-- Startup Speed & Low-RAM Footprint Optimizations -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <TieredPGO>true</TieredPGO>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app_icon.png" />
    <Resource Include="Assets\app_icon.ico" />
    <Resource Include="Assets\Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\bin\yt-dlp.exe" Condition="Exists('..\..\bin\yt-dlp.exe')">
      <Link>bin\yt-dlp.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\bin\aria2c.exe" Condition="Exists('..\..\bin\aria2c.exe')">
      <Link>bin\aria2c.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.6.2" />
  </ItemGroup>

</Project>
